site_name: coilysiren/cli-web-docs
site_description: Static HTML documentation generator for urfave/cli v3
site_url: https://coilysiren.github.io/cli-web-docs/
repo_url: https://github.com/coilysiren/cli-web-docs
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Features: FEATURES.md
  - Examples: examples.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Security: SECURITY.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: light mode
  features:
    - content.code.annotate
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - git-revision-date-localized
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
